import { getSiteUrlFromRequest } from "@config/index";
import { buildSitemapIndex } from "@utils/sitemap";
import { NextRequest } from "next/server";

export async function GET(request: NextRequest) {
  // Get site URL from request (prefers request host, falls back to env-based detection)
  const siteUrl = getSiteUrlFromRequest(request);

  // Build sitemap index referencing all sitemaps
  // This matches the structure of public/sitemap.xml generated by next-sitemap
  const sitemapUrls = [
    `${siteUrl}/sitemap-0.xml`, // Generated by next-sitemap (may not exist in dev)
    `${siteUrl}/server-sitemap.xml`,
    `${siteUrl}/server-news-sitemap.xml`,
    `${siteUrl}/server-place-sitemap.xml`,
    `${siteUrl}/server-google-news-sitemap.xml`,
  ];

  const xml = buildSitemapIndex(sitemapUrls);
  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      // Enable caching at the edge/CDN
      "Cache-Control": "public, s-maxage=600, stale-while-revalidate=86400",
    },
    status: 200,
  });
}
