import { getSiteUrlFromRequest } from "@config/index";
import { buildSitemapIndex } from "@utils/sitemap";
import { NextRequest } from "next/server";

export async function GET(request: NextRequest) {
  // Get site URL from request (prefers request host, falls back to env-based detection)
  const siteUrl = getSiteUrlFromRequest(request);

  // Build sitemap index referencing all sitemaps
  // This matches the structure of public/sitemap.xml generated by next-sitemap
  const sitemapUrls = [
    `${siteUrl}/server-static-sitemap.xml`, // Replaces sitemap-0.xml (static pages)
    `${siteUrl}/server-sitemap.xml`,
    `${siteUrl}/server-news-sitemap.xml`,
    `${siteUrl}/server-place-sitemap.xml`,
    `${siteUrl}/server-google-news-sitemap.xml`,
  ];

  const xml = buildSitemapIndex(sitemapUrls);

  // Check for cache-busting query parameter (e.g., ?v=2 or ?nocache=1)
  const hasCacheBust =
    request.nextUrl.searchParams.has("v") ||
    request.nextUrl.searchParams.has("nocache");

  // Reduced cache TTL: 5 minutes at edge, no stale-while-revalidate to prevent serving old content
  // If cache-busting is requested, disable caching entirely
  const cacheControl = hasCacheBust
    ? "no-cache, no-store, must-revalidate"
    : "public, s-maxage=300, stale-while-revalidate=0";

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": cacheControl,
    },
    status: 200,
  });
}
