nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  "@sentry/nextjs@*":
    peerDependencies:
      "@opentelemetry/api": "*"
      "@opentelemetry/context-async-hooks": "*"
      "@opentelemetry/core": "*"
      "@opentelemetry/sdk-trace-base": "*"
      react: "*"
      # webpack is provided by Next.js internally, no need to install
      webpack: "*"
  "@types/react-datepicker@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
