import { test, expect } from "@playwright/test";

test.describe("Filters Modal Interaction", () => {
  test.beforeEach(async ({ context }) => {
    // Grant geolocation permissions and set a mock location
    await context.grantPermissions(["geolocation"]);
    await context.setGeolocation({ latitude: 41.3851, longitude: 2.1734 });
  });

  test("should open modal, set distance, trigger geolocation, and apply filters", async ({
    page,
  }) => {
    // 1. Navigate to the page
    await page.goto("/catalunya", { waitUntil: "domcontentloaded" });

    // 2. Open the filters modal
    const filterButton = page.getByTestId("filters-open");
    await expect(filterButton).toBeVisible();
    await filterButton.click({ force: true });

    // 3. Verify modal is open using data-testid
    const modal = page.getByTestId("filters-modal");
    await expect(modal).toBeVisible({ timeout: 10000 });
    
    // Verify content inside modal
    await expect(modal.getByText("Poblacions")).toBeVisible();
    await expect(modal.getByText("Distància")).toBeVisible();

    // 4. Interact with the range slider
    // Target the input inside the wrapper with data-testid
    const rangeInput = page.locator('[data-testid="distance-range"] input[type="range"]');
    await expect(rangeInput).toBeVisible();

    // Initial value should be 50 (default)
    await expect(rangeInput).toHaveValue("50");

    // Change the value to 30
    await rangeInput.evaluate((el, value) => {
      (el as HTMLInputElement).value = value;
      el.dispatchEvent(new Event("input", { bubbles: true }));
      el.dispatchEvent(new Event("change", { bubbles: true }));
    }, "30");

    // Verify the visual feedback updated (e.g., "30 km")
    await expect(page.getByText("30 km")).toBeVisible();

    // 5. Verify "Selecciona població" becomes disabled
    // Target the select input by ID (generated by Select component as `${id}-input`)
    const placeInput = page.locator('input#options-input');
    await expect(placeInput).toBeDisabled();

    // 6. Apply filters using data-testid
    const applyButton = page.getByTestId("filters-modal-action-button");
    await expect(applyButton).toBeVisible();
    await applyButton.click();

    // 7. Verify URL updates
    // Should contain distance=30 and lat/lon from our mock
    await page.waitForURL((url) => url.searchParams.has("distance"), { timeout: 10000 });
    
    const url = new URL(page.url());
    expect(url.searchParams.get("distance")).toBe("30");
    expect(url.searchParams.get("lat")).toBe("41.3851");
    expect(url.searchParams.get("lon")).toBe("2.1734");
    
    // Place should be 'catalunya' (default when distance is used)
    expect(url.pathname).toMatch(/^\/catalunya/);
  });

  test("should disable place input when distance is active", async ({ page }) => {
    await page.goto("/catalunya", { waitUntil: "domcontentloaded" });
    
    const filterButton = page.getByTestId("filters-open");
    await expect(filterButton).toBeVisible();
    await filterButton.click({ force: true });
    
    const modal = page.getByTestId("filters-modal");
    await expect(modal).toBeVisible({ timeout: 10000 });
    
    const rangeInput = page.locator('[data-testid="distance-range"] input[type="range"]');
    await rangeInput.evaluate((el, value) => {
      (el as HTMLInputElement).value = value;
      el.dispatchEvent(new Event("input", { bubbles: true }));
      el.dispatchEvent(new Event("change", { bubbles: true }));
    }, "25");
    
    await expect(page.getByText("25 km")).toBeVisible();
    
    // Check disabled state
    const placeInput = page.locator('input#options-input');
    await expect(placeInput).toBeDisabled();
  });
});
