#!/usr/bin/env node

/**
 * Generates public/robots.txt at build time.
 *
 * WHY THIS EXISTS:
 * Ensures robots.txt is always present as a static file in the build output,
 * providing reliable serving regardless of the deployment platform.
 * The route handler (app/robots.txt/route.ts) serves as a fallback.
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");

// Get site URL from environment or use default
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  process.env.NEXT_PUBLIC_VERCEL_URL ||
  "https://www.esdeveniments.cat";

// Normalize URL (remove trailing slash, ensure https)
const normalizedSiteUrl = siteUrl.replace(/\/$/, "").replace(/^http:/, "https:");

// Detect non-production hosts (staging, PR previews, dev) — these must not
// be indexed. GSC reported ~7,800 staging URLs leaking into Google's index
// because robots.txt allowed everything and no X-Robots-Tag was emitted.
//
// Default-deny: anything not on the production allowlist below is treated as
// non-production. Substring checks (e.g. `pr-`) silently fail if Coolify's
// PR-preview URL template changes.
//
// KEEP IN SYNC WITH `utils/production-host.ts` (runtime copy).
const PRODUCTION_HOSTS = new Set([
  "www.esdeveniments.cat",
  "esdeveniments.cat",
]);
let isNonProductionHost = true;
try {
  isNonProductionHost = !PRODUCTION_HOSTS.has(
    new URL(normalizedSiteUrl).hostname.toLowerCase(),
  );
} catch {
  // Malformed URL → treat as non-production (safer default).
  isNonProductionHost = true;
}

/**
 * robots.txt configuration - KEEP IN SYNC with app/robots.txt/route.ts
 *
 * 2026 policy — AI-agent-first discoverability:
 * - Allow search engine crawlers (Googlebot, Bingbot, etc.)
 * - Allow AI agent crawlers (browsing + training) so LLM citations,
 *   deep-research tools, and agent-readiness scanners (orank.ai
 *   sim-chatgpt / sim-claude) can reach our content. Our data is
 *   public cultural-events information; training protection has
 *   lower value than broad agent reach.
 * - Block /_next/ static files (JS chunks, CSS, build artifacts)
 * - Block /api/ routes (internal endpoints, not for indexing)
 */
const robotsConfig = {
  rules: [
    // Default rules for all crawlers (including search engines)
    {
      userAgent: "*",
      allow: ["/"],
      disallow: ["/_next/", "/api/", "/e2e/", "/offline/", "/login/"],
    },
    // AI agent BROWSING/SEARCH crawlers — explicit allow (agent readiness)
    { userAgent: "ChatGPT-User", allow: ["/"] },
    { userAgent: "Claude-Web", allow: ["/"] },
    { userAgent: "PerplexityBot", allow: ["/"] },
    { userAgent: "DeepSeekBot", allow: ["/"] },
    // AI TRAINING crawlers — explicit allow (2026 policy; see header).
    // Removing these explicit rules would also allow them (via `*`), but we
    // list them to make the policy visible to maintainers and to scanners.
    { userAgent: "GPTBot", allow: ["/"] },
    { userAgent: "ClaudeBot", allow: ["/"] },
    { userAgent: "anthropic-ai", allow: ["/"] },
    { userAgent: "Google-Extended", allow: ["/"] },
    { userAgent: "Applebot-Extended", allow: ["/"] },
    { userAgent: "Meta-ExternalAgent", allow: ["/"] },
    { userAgent: "cohere-ai", allow: ["/"] },
    // Still-blocked: non-vendor data harvesters with no direct user-agent
    // value. These resell scraped data without powering any end-user agent.
    { userAgent: "CCBot", disallow: ["/"] },
    { userAgent: "Bytespider", disallow: ["/"] },
    { userAgent: "Omgilibot", disallow: ["/"] },
  ],
  sitemaps: [
    `${normalizedSiteUrl}/sitemap.xml`,
    `${normalizedSiteUrl}/server-static-sitemap.xml`,
    `${normalizedSiteUrl}/server-sitemap.xml`,
    `${normalizedSiteUrl}/server-news-sitemap.xml`,
    `${normalizedSiteUrl}/server-place-sitemap.xml`,
    `${normalizedSiteUrl}/server-google-news-sitemap.xml`,
  ],
  host: normalizedSiteUrl,
};

// On non-production hosts (staging, PR previews), block all crawlers and
// strip sitemaps. Disallow-all on User-Agent: * fully blocks indexing.
if (isNonProductionHost) {
  robotsConfig.rules = [
    {
      userAgent: "*",
      disallow: ["/"],
    },
  ];
  robotsConfig.sitemaps = [];
}

function generateRobotsTxt() {
  const lines = [];

  // Add generation timestamp
  lines.push(`# Generated by scripts/generate-robots.mjs at ${new Date().toISOString()}`);
  lines.push(`# Site URL: ${normalizedSiteUrl}`);
  lines.push("");

  // Add rules
  for (const rule of robotsConfig.rules) {
    lines.push(`User-Agent: ${rule.userAgent}`);

    if (rule.allow) {
      for (const path of rule.allow) {
        lines.push(`Allow: ${path}`);
      }
    }

    if (rule.disallow) {
      for (const path of rule.disallow) {
        lines.push(`Disallow: ${path}`);
      }
    }

    lines.push("");
  }

  // Add host
  lines.push(`Host: ${robotsConfig.host}`);
  lines.push("");

  // Add sitemaps
  for (const sitemap of robotsConfig.sitemaps) {
    lines.push(`Sitemap: ${sitemap}`);
  }

  // Content Signals
  lines.push("");
  lines.push("# Content Signals — AI usage preferences");
  lines.push("Content-Signal: ai-train=no, search=yes, ai-input=yes");

  // Schema feed directive
  lines.push("");
  lines.push("# Schema feed for structured data discovery");
  lines.push(`schemamap: ${normalizedSiteUrl}/openapi.json`);

  return lines.join("\n");
}

// Generate and write robots.txt
const robotsTxt = generateRobotsTxt();
const outputPath = join(rootDir, "public", "robots.txt");

writeFileSync(outputPath, robotsTxt, "utf-8");

console.log(`✅ Generated ${outputPath}`);
console.log(`   Site URL: ${normalizedSiteUrl}`);
const blocked = robotsConfig.rules.filter((r) => r.disallow && !r.allow).length;
const allowed = robotsConfig.rules.filter((r) => r.allow).length;
console.log(`   User-agent rules: ${allowed} allow, ${blocked} disallow`);
